name: 'BitBlazor - Test runner'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

#permissions:
#  checks: write
    
jobs:
  build_and_test:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'BitBlazor.sln'
      PROJECT_NAME: src/BitBlazor

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x

    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG
      
    - name: Test
      run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-runner-results.trx" || true

    # DEPRECATED - see #70
    #- name: Test Report
    #  uses: dorny/test-reporter@v1
    #  if: always()
    #  with:
    #    name: DotNET Tests
    #    path: "**/test-runner-results.trx"                            
    #    reporter: dotnet-trx
    #    fail-on-error: true

    - uses: actions/upload-artifact@v4  # upload test results
      if: ${{ !cancelled() }}           # run this step even if previous step failed
      with:
        name: dotnet-test-results
        path: test-runner-results.trx